In [5]:
import pandas as pd

In [6]:
results = "trade_results.csv"
df = pd.read_csv(results)
df

       Epoch          Time  Price 売買アクション  報酬額
0          0  1.748822e+09   3363    新規売り    0
1          0  1.748822e+09   3363    ホールド    0
2          0  1.748822e+09   3363    ホールド    0
3          0  1.748822e+09   3363    ホールド    0
4          0  1.748822e+09   3359    ホールド    0
...      ...           ...    ...     ...  ...
58267      2  1.748845e+09   3342    ホールド    0
58268      2  1.748845e+09   3342    ホールド    0
58269      2  1.748845e+09   3342    ホールド    0
58270      2  1.748845e+09   3342    ホールド    0
58271      2  1.748845e+09   3343    ホールド    0

[58272 rows x 5 columns]

In [7]:
print("出力データ:", results)
for epoch in sorted(set(df["Epoch"])):
    df0 = df[df["Epoch"] == epoch]
    print("Epoch:", epoch, "報酬額:", df0["報酬額"].sum())

出力データ: trade_results.csv
Epoch: 0 報酬額: 4300
Epoch: 1 報酬額: -4200
Epoch: 2 報酬額: 9900